language: python
python:
  - "3.6"      # current default Python on Travis CI

# command to install dependencies
install:
  - sudo apt-get install php
  - pip install -r requirements.txt

# launch website so it can be tested
before_script:
  - "php -S localhost:8000"

# command to run tests
script:
  - coverage run unitTests.py

after_success:
  - coveralls